# Generated by Django 5.2.1 on 2025-05-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rename_create_at_uploadedfile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
