# Generated by Django 5.2.1 on 2025-05-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uploadedfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
